In [1]:
import pandas as pd


temp = pd.read_csv("../../prediction/klue-roberta-largeRECENT/klue-roberta-largeRECENT_none_b8_e10_lr1e-05.csv")

In [2]:
temp

        id   pred_label                                         probs
0        0     relation   [0.0013091915752738714, 0.9986907839775085]
1        1     relation   [0.0009650670690461993, 0.9990350008010864]
2        2  no_relation   [0.9999938011169434, 6.238134119485039e-06]
3        3  no_relation     [0.990559995174408, 0.009440007619559765]
4        4     relation      [0.40478622913360596, 0.595213770866394]
...    ...          ...                                           ...
7760  7760     relation    [0.006221110001206398, 0.9937788844108582]
7761  7761  no_relation    [0.9995023012161255, 0.000497673696372658]
7762  7762     relation  [1.3454420695779845e-05, 0.9999865293502808]
7763  7763     relation     [0.04298783466219902, 0.9570121765136719]
7764  7764  no_relation   [0.9988510608673096, 0.0011489398311823606]

[7765 rows x 3 columns]

In [3]:
change_list = []
for i in range(len(temp)):
    if temp["pred_label"][i] == "relation":
        change_list.append("per:title")
    else:
        change_list.append("no_relation")

temp["pred_label"] = change_list

In [4]:
temp

        id   pred_label                                         probs
0        0    per:title   [0.0013091915752738714, 0.9986907839775085]
1        1    per:title   [0.0009650670690461993, 0.9990350008010864]
2        2  no_relation   [0.9999938011169434, 6.238134119485039e-06]
3        3  no_relation     [0.990559995174408, 0.009440007619559765]
4        4    per:title      [0.40478622913360596, 0.595213770866394]
...    ...          ...                                           ...
7760  7760    per:title    [0.006221110001206398, 0.9937788844108582]
7761  7761  no_relation    [0.9995023012161255, 0.000497673696372658]
7762  7762    per:title  [1.3454420695779845e-05, 0.9999865293502808]
7763  7763    per:title     [0.04298783466219902, 0.9570121765136719]
7764  7764  no_relation   [0.9988510608673096, 0.0011489398311823606]

[7765 rows x 3 columns]

In [8]:
chagne_probs = [0.1 for i in range(30)]
change_probs = [chagne_probs for i in range(len(temp))]

In [9]:
temp["probs"] = change_probs

In [10]:
temp.to_csv("temp.csv")